let mapleader=","

set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

" My plugins

Plugin 'sheerun/vim-polyglot'
Plugin 'tpope/vim-rails'
Plugin 'tpope/vim-rake'
Plugin 'tpope/vim-bundler'
"Plugin 'thoughtbot/vim-rspec'
Plugin 'scrooloose/nerdtree'
"Plugin 'jlanzarotta/bufexplorer'
Plugin 'scrooloose/nerdcommenter'
"Plugin 'vim-scripts/ctrlp.vim'
Plugin 'mileszs/ack.vim' " search in files
Plugin 'skwp/greplace.vim' " Gsearch and Greplace for text in files
Plugin 'coderifous/textobj-word-column.vim' " Visually select columns
"Plugin 'hail2u/vim-css3-syntax'
Plugin 'tpope/vim-endwise' " Smart function ending
Plugin 'tpope/vim-eunuch' " Unix commands
Plugin 'kopischke/vim-fetch' "Go to line and column in files
Plugin 'tpope/vim-fugitive' " Git integration
Plugin 'tpope/vim-unimpaired'   " Shortcuts for git integration
Plugin 'pangloss/vim-javascript' " JS highlighting
Plugin 'christoomey/vim-rfactory' " Rfactory for navigating to factories
Plugin 'mtth/scratch.vim' " Scratch pad
"Plugin 'christoomey/vim-system-copy' " System clipboard copy
Plugin 'christoomey/vim-tmux-navigator' " tmux / vim navigation
"Plugin 'Syntastic'   " syntax checking
Plugin 'w0rp/ale' " syntax checking
Plugin 'terryma/vim-multiple-cursors'
Plugin 'tpope/vim-repeat'
Plugin 'surround.vim'
Plugin 'airblade/vim-gitgutter'
"Plugin 'ervandew/supertab'
Plugin 'tpope/vim-abolish'
Plugin 'MattesGroeger/vim-bookmarks' " bookmarks
" Pane plugins for vim-test
Plugin 'janko-m/vim-test' " Shortcuts for testing
"Plugin 'christoomey/vim-tmux-runner'
"Plugin 'tpope/vim-dispatch'  " TPope's test integration
Plugin 'jgdavey/tslime.vim' " Not the original
"Plugin 'kassio/neoterm'
Plugin 'terryma/vim-smooth-scroll' " Smooth scrolling

" Fuzzy Finder
Plugin 'junegunn/fzf', { 'dir': '~/.fzf', 'do': './install --all' }
Plugin 'junegunn/fzf.vim'
"Plugin 'vim-scripts/ctrlp.vim'

" Airline styling
"Plugin 'vim-airline/vim-airline'
"Plugin 'vim-airline/vim-airline-themes'
Plugin 'flazz/vim-colorschemes'
Plugin 'rizzatti/dash.vim'
Plugin 'joonty/vdebug'
Plugin 'kburdett/vim-nuuid' " uuid gen

" Tags for code lookup
Plugin 'ludovicchabant/vim-gutentags'
let g:gutentags_cache_dir = '~/.tags_cache'

" Completions
Plugin 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
let g:deoplete#enable_at_startup = 1
" use tab for completion
inoremap <expr><tab> pumvisible() ? "\<c-n>" : "\<tab>"

" Better terminal integration, cursor shapes, buffer updates
Plugin 'wincent/terminus'
Plugin 'slashmili/alchemist.vim'


" All of your Plugins must be added before the following line
call vundle#end()            " required

filetype plugin indent on    " required

set ttyfast " Faster redrawing

syntax on

" set autoindent                " copy indent from current line when starting a new line
set background=dark           " use colors that look good on dark
set backspace+=eol            " allow backspacing over line breaks (join lines)
set backspace+=indent         " allow backspacing over autoindent
set backspace+=start          " allow backspacing over the start of insert; CTRL-W and CTRL-U
set clipboard=unnamedplus         " yanks to osx clipboard
set cursorline                " highlight the screen line of the cursor
set expandtab                 " expand tabs to spaces
set hidden                    " allow buffers to be hidden
set history=1000              " number of history items to remember
set hlsearch                  " highlight search pattern matches
set ignorecase                " ignore case"
set incsearch                 " highlight search pattern matches as they're found
set iskeyword+=-              " allow - to be considered part of a word
"set laststatus=1              " only show status if there are at least 2 windows
set matchtime=2               " amount of time to show the matching parent when 'showmatch' is set
set number relativenumber     " display line numbers and relative numbers
set nojoinspaces              " add single space after '.', '?', and '!' with a join command
set noswapfile                " do not make a swapfile
set nowrap                    " default to no line wrapping
set ruler                     " show line and column number of the cursor position
set scrolloff=3               " minimum number of screen lines to keep above/below the cursor"
set shiftwidth=2              " set indent to 2 spaces
set showmatch                 " when a bracket is inserted, briefly jump to the matching one
set smartcase                 " ignore case when the pattern contains lowercase only"
set softtabstop=2             " set <tab> to 2 spaces while in insert mode
set tabstop=2                 " set <tab> to two spaces
set wildmenu                  " enable command-completion window
set wildmode=list:longest     " list all matches and complete til longest common match
set listchars+=tab:\ \
set termguicolors
"set tags+='~/.tags_cache'

" Find in files
map <leader>f :Ack!<space>

if executable('ag')
  let g:ackprg = 'ag --vimgrep'
endif

" Fuzzy finder
nnoremap <c-p> :Files<CR>
nnoremap <leader>r :BTags<CR>
nnoremap <leader>e :Buffers<CR>

let g:fzf_layout = { 'down': '~40%' }
let $FZF_DEFAULT_COMMAND = 'ag --hidden --ignore .git -g ""'
let g:fzf_action = {  'ctrl-t': 'tab split', 'ctrl-h': 'split', 'ctrl-v': 'vsplit' }

"let g:ctrlp_extensions = ['buffertag']
"nnoremap <leader>r :CtrlPBufTag<CR>

" Save and Reload sessions
map <F2> :mksession! ~/.vim_session <cr> " Quick write session with F2
map <F3> :source ~/.vim_session <cr>     " And load session with F3
" For vim-javascript
"let g:javascript_enable_domhtmlcss = 1
"let g:javascript_ignore_javaScriptdoc = 1

" Scratch pad options
" let g:scratch_horizontal = 1
" let g:scratch_height = 20
let g:scratch_persistence_file = 'project-notes.txt'

" Vim-Test options
"let test#strategy = "neoterm"
"let test#strategy = "neovim"
"let g:neoterm_position = "vertical"

let test#strategy = "tslime"
"let test#strategy = "vtr"
"let test#ruby#bundle_exec = 0
"let g:VtrOrientation = "h"
"let g:VtrPercentage = 20

" Tmux runner configuration
nmap <silent> <leader>s :TestNearest<CR>
nmap <silent> <leader>t :TestFile<CR>
nmap <silent> <leader>a  :TestSuite<CR>
nmap <silent> <leader>l :TestLast<CR>
nmap <silent> <leader>v :TestVisit<CR>
"nmap <silent> <leader>r :Tmux rubocop<CR>

nnoremap <leader>ra :VtrAttachToPane<cr>
nnoremap <leader>rO :VtrReorientRunner<cr>
nnoremap <leader>rc :VtrSendCommandToRunner<cr>
nnoremap <leader>rl :VtrSendLinesToRunner<cr>
nnoremap <leader>ro :VtrOpenRunner<cr>
nnoremap <leader>rk :VtrKillRunner<cr>
nnoremap <leader>rf :VtrFocusRunner<cr>
nnoremap <leader>rd :VtrDetachRunner<cr>
nnoremap <leader>rC :VtrClearRunner<cr>

fun! <SID>StripTrailingWhitespaces()
    let l = line(".")
    let c = col(".")
    %s/\s\+$//e
    call cursor(l, c)
endfun
autocmd BufWritePre * :call <SID>StripTrailingWhitespaces()

" Reload vim on vimrc changes
autocmd! BufWritePost ~/.vim/vimrc  source ~/.vim/vimrc       " source .vimrc on save
autocmd! VimResized * :wincmd =                       " automatically rebalance windows on vim resize

nnoremap j gj
nnoremap k gk
inoremap jj <ESC>
inoremap jk <ESC>
inoremap <F1> <ESC>
nnoremap <F1> <ESC>
vnoremap <F1> <ESC>

nnoremap <c-w>[ :wincmd _<cr><bar>:wincmd \|<cr>                " zoom in the active window
nnoremap <c-w>] :wincmd =<cr>                                   " zoom out the current window

" Sublime like multiple cursors
let g:multi_cursor_exit_from_insert_mode = 0
let g:multi_cursor_exit_from_visual_mode = 0

" Only highlight the screen line of the active buffer
augroup CursorLine
  au!
  au VimEnter,WinEnter,BufWinEnter * setlocal cursorline
  au WinLeave * setlocal nocursorline
augroup END

" Map arrow keys to window resize
nmap <left>  <c-w><
nmap <right> <c-w>>
nmap <up>    <c-w>+
nmap <down>  <c-w>-

" Smooth scrolling
noremap <silent> <c-u> :call smooth_scroll#up(&scroll/2, 0, 2)<CR>
noremap <silent> <c-d> :call smooth_scroll#down(&scroll/2, 0, 2)<CR>
noremap <silent> <c-b> :call smooth_scroll#up(&scroll, 0, 4)<CR>
noremap <silent> <c-f> :call smooth_scroll#down(&scroll, 0, 4)<CR>

" Toggle Nerd Tree
map <leader>n :NERDTreeToggle<CR>
nnoremap <leader>d :Dash<CR>

"This unsets the 'last search pattern' register by hitting return
nnoremap <CR> :noh<CR><CR>

" Set airline theme
colorscheme molokai
"let g:airline_theme='molokai'

" Settings for Ale
"let g:ale_linters = { 'javascript': ['standard'], }
let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_enter = 0
let g:ale_sign_column_always = 1
let g:ale_statusline_format = ['⨉ %d', '⚠ %d', '⬥ ok']
let g:ale_javascript_eslint_executable = 'eslint_d'
let g:ale_sign_error = '✗'
let g:ale_sign_warning = '⚠'

augroup AleGroup
    autocmd!
    autocmd User ALELint call TouchOpenFile()
augroup END

func! TouchOpenFile()
    let g:ale_enabled = 0
    sleep 500m
    w
    let g:ale_enabled = 1
endfunc
" Syntastic
"set statusline+=%#warningmsg#
"set statusline+=%{SyntasticStatuslineFlag()}
"set statusline+=%*
"set statusline+=%h%M%r%w

"set statusline=[%n]\ %<%.99f\ %h%w%m%r%{exists('*CapsLockStatusline')?CapsLockStatusline():''}%y%=%-16(\ %l,%c-%v\ %)%P

"let g:syntastic_always_populate_loc_list = 1
"let g:syntastic_auto_loc_list = 0
"let g:syntastic_check_on_open = 1
"let g:syntastic_check_on_wq = 0
"let g:syntastic_javascript_checkers = ['jshint']
"let g:syntastic_loc_list_height = 5


